on:
  push:
    paths:
      - sketchbooks/**

jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
        with:
          sketch-paths: |
            - sketchbooks/